### ISSUE TITLE
Troubles running picopc on Windows Server 2016

### ISSUE THREAD

**Issue by panwolfram** [tallakt/picopc#1]
Hi,
I need to connect to Matrikon OPC from Ruby on Windows Server 2016.
After installing your gem, it turned out that I need to correct `ei` variable to `e` in `lib/picopc/picopc.rb`.
It wasn't big deal, but there's a bigger one: I can't connect to my Matrikon Simulation server.
According to your guide, I've fired up irb and executed:
```
require 'picopc'; PicOpc::Client.new 'Matrikon.OPC.Simulation.1'
```
but I'm getting the following error message:

```
irb(main):002:0> require 'picopc'; PicOpc::Client.new 'Matrikon.OPC.Simulation.1'
PicOpc::PicOpcException: OPC/OLE Exceptioni Connecting to: Matrikon.OPC.Simulation.1: unknown OLE server: `OPC.Automation.1'
    HRESULT error code:0x800401f3
      Invalid class string
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tallakt-picopc-0.1.2/lib/picopc/olegen_opc_automation.rb:1705:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tallakt-picopc-0.1.2/lib/picopc/olegen_opc_automation.rb:1705:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tallakt-picopc-0.1.2/lib/picopc/olegen_opc_automation.rb:1705:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tallakt-picopc-0.1.2/lib/picopc/picopc.rb:36:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tallakt-picopc-0.1.2/lib/picopc/picopc.rb:36:in `initialize'
        from (irb):2:in `new'
        from (irb):2
        from C:/Ruby24-x64/bin/irb.cmd:19:in `<main>'
```

I believe it's about `OPC.Automation.1` which you've defined in `olegen....rb`, but I don't know with which value to replace it.

What I should to to make it working?
Thanks in advance,
Mike Wolfram

**Comment by tallakt** [comment]
Hi. It's been a while since I wrote this. It's always been fluky unfortunately, due to COM/DCOM. But it did work ok at a point, and I guess it should still.

To find the list of availale servers, you should call the OLE method `def GetOPCServers(arg0=nil)`. You might see that one of these files are autogenerated. 

Like this:

```
Z:\>cd "Z:\Prosjekt\tmp\picopc-master\lib\picopc"
Z:\Prosjekt\tmp\picopc-master\lib\picopc>irb -r ./olegen_opc_automation 
irb(main):001:0> opc_automation = OPC_Automation_1.new
=> #<OPC_Automation_1:0x2c02f50 @clsid="{28E68F9A-8D75-11D1-8DC3-3C302A000000}", @progid="OPC.Automation.1", @dispatch=#<WIN32OLE:0x2c02ed8>>
irb(main):002:0> opc_automation.GetOPCServers
=> ["ArchestrA.FSGateway", "PhoenixContact.AX-Server", "PhoenixContact.AX-Server.21"]
irb(main):003:0>
```

As you can see, Matrikon is not on my list. I only have the explorer installed and not the server.

Hope this helps!

For the other thins (e -> ei), please submit a pull request...

**Comment by tallakt** [comment]
Please look at the gem in version 0.1.1. You may now run:

```
  > ruby -r picopc -e 'p PicOpc::list_opc_servers'
  ["ArchestrA.FSGateway", "PhoenixContact.AX-Server", "PhoenixContact.AX-Server.21"]
```

**Comment by panwolfram** [comment]
Hello,
I’ve tried your suggestions but none of them worked.
I’ve even installed the latest version of gem from git.
All I get is an error message saying that OPC.Automation.1 is unknown.
Here’s the screenshot of it:

![pastedgraphic-3](https://user-images.githubusercontent.com/4481886/30633402-ca55e956-9deb-11e7-9ecc-dc30e0c971f8.png)

Here’s the result of suggestions from your first message - and I’ve ended up with the same error:

![pastedgraphic-5](https://user-images.githubusercontent.com/4481886/30633570-6a79d7a8-9dec-11e7-893a-e2f4789906ee.png)

**Comment by tallakt** [comment]
The Ole.Automation.1 is installed ad a standard mechanism to find any OPC servers installed on your system. As you can't use it I would expect that you dont have any OPC servers installed, as they all install this 'driver' first. If you have such installed, there must be another reason that you can't instanciate it. 

Have you tried a standard OPC server and connected to it using a standard OPC browser (eg matrikon opc explorer and matrikon opc simulation server)?

**Comment by panwolfram** [comment]
I’ve got Matrikon Explorer set up on my machine.
From it, I can connect to Matrokon.OPC.Simulation.1. or Matrikon.OPC.SiemensPLC.1 and it works fine.

I’ve also connected to both of them from Python:

C:\Users\username>C:\Python27\python.exe
Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenOPC
>>> opc = OpenOPC.client()
>>> opc.connect('Matrikon.OPC.SiemensPLC.1')
>>> print opc['TCP>ISO>#Latency']
156.0

**Comment by tallakt** [comment]
Thanks for looking into this.

could you try this in a command window?

```
C:\>irb -r win32ole
irb(main):001:0> sl = WIN32OLE.new "OPC.Automation.1"
=> #<WIN32OLE:0x3067350>
irb(main):002:0>
```

Perhaps also for different numbers instead of `.1` ...

**Comment by tallakt** [comment]
Also please version of Ruby and Windows....

**Comment by panwolfram** [comment]
Here’s the screenshot of few tries I’ve made - none of them worked:

![pastedgraphic-6](https://user-images.githubusercontent.com/4481886/30638770-d171756e-9dfc-11e7-8e2f-f4952f8feafd.png)

Ruby version:
C:\Users\username>ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

**Comment by tallakt** [comment]
I am wondering if you installed Ruby with the windows installer or some other means?

**Comment by panwolfram** [comment]
I’ve installed Ruby with rubyinstaller-2.4.1-1-x64.exe from https://rubyinstaller.org/downloads/archives/ <https://rubyinstaller.org/downloads/archives/>.

**Comment by tallakt** [comment]
How about:

```
> OPC = "Matrikon.OPC.Automation;Graybox.OPC.DAWrapper;HSCOPC.Automation;RSI.OPCAutomation;OPC.Automation"
> sl = WIN32OLE.new OPC
```

**Comment by pboling** [comment]
I am having the same trouble as @panwolfram, and I must get this working, so I am digging in.
Here is the result of your last suggestion:
```
irb(main):014:0> OPC = "Matrikon.OPC.Automation;Graybox.OPC.DAWrapper;HSCOPC.Automation;RSI.OPCAutomation;OPC.Automation"
=> "Matrikon.OPC.Automation;Graybox.OPC.DAWrapper;HSCOPC.Automation;RSI.OPCAutomation;OPC.Automation"
irb(main):015:0> sl = WIN32OLE.new OPC
WIN32OLERuntimeError: unknown OLE server: `Matrikon.OPC.Automation;Graybox.OPC.DAWrapper;HSCOPC.Automation;RSI.OPCAutomation;OPC.Automation'
    HRESULT error code:0x800401f3
      Invalid class string
        from (irb):15:in `initialize'
        from (irb):15:in `new'
        from (irb):15
        from bin/console:14:in `<main>'
```

I am on Windows 10, running Ruby 2.4.3:
```
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\pboling>ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
```

@tallakt thanks for still being responsive on this issue after so many years!!  As I've been researching this I've been finding your investigation posts on various forums from years ago, and they have been helpful.

**Comment by pboling** [comment]
It is clear that this issue is not actually a problem if the picopc library.
```
irb(main):022:0> w = WIN32OLE.new 'Graybox.Simulator.1'
WIN32OLERuntimeError: failed to create WIN32OLE object from `Graybox.Simulator.1'
    HRESULT error code:0x80004002
      No such interface supported
        from (irb):22:in `initialize'
        from (irb):22:in `new'
        from (irb):22
        from bin/console:14:in `<main>'
```
I have Graybox and Matrikon simulators running on this machine, and both give me the same error.

I did use the windows installer to get my Ruby, and I am wondering if there is a disconnect somewhere.

Interestingly, I can use the WIN32OLE library to access other things on the system:
```
irb(main):017:0> WIN32OLE.new('Excel.Application')
=> #<WIN32OLE:0x00000000059fbcd0>
```

**Comment by tallakt** [comment]
Hi. I'm sorry I'm no longer in a position to maintain this. I use only mac and linux atm. and very little OPC also.. I'd be happy to add any sensible pull requests...

I think ideally the MS COM solution for OPC does not work that well as we see here, and the way forward would be a OPC UA implementation. But this is hard due to OPC's insistence on not making the standard open for non paying members.

**Comment by pboling** [comment]
I think I am going to take the advice in your readme and try a Python solution you mentioned.  👍

**Comment by konimarti** [comment]
@pboling @panwolfram This might come too late for your projects but have you tried a 32bit Ruby version? I ran into a similar problem on another OPC project and could solve it that way.

**Comment by pboling** [comment]
@konimarti I have moved on from that project.  I was never able to get anything working in Ruby, and didn't have the time to dig deep enough to figure out why.

**Comment by panwolfram** [comment]
In the end I used OpenOPC, Python library, which worked fine in my case.
